#include "kproj.h"
#include "vfs.h"
#include "uart.h"
#include "string.h"

void kproj_execute(const char *name) {
    if (!name || strlen(name) == 0) {
        uart_puts("Usage: kproj <project_name>\n");
        return;
    }

    uart_printf("\033[36m[*] Scaffolding Kaviraj OS Project: %s\033[0m\n", name);

    if (vfs_mkdir(name) != 0) {
        uart_puts("\033[31m[-] Error: Could not create project directory.\033[0m\n");
        return;
    }

    // Enter project directory
    vfs_chdir(name);

    // Scaffold architecture
    vfs_mkdir("src");
    vfs_mkdir("tests");
    
    // Create main.py
    char main_py_content[256];
    strcpy(main_py_content, "def main():\n    print('Welcome to ");
    strcat(main_py_content, name);
    strcat(main_py_content, "!')\n\nif __name__ == '__main__':\n    main()\n");
    vfs_touch("main.py", main_py_content);

    // Create requirements.txt
    vfs_touch("requirements.txt", "# Add Python dependencies here\n");

    // Create README.md
    char readme_content[128];
    strcpy(readme_content, "# ");
    strcat(readme_content, name);
    strcat(readme_content, "\n\nGenerated by Kaviraj OS Agent.\n");
    vfs_touch("README.md", readme_content);

    // Sync to disk
    vfs_sync();

    uart_puts("\033[32m[+] Project scaffolded successfully.\033[0m\n");
    uart_printf("    Enter with: \033[1;33mcd %s\033[0m\n\n", name);
    
    // Return to parent directory
    vfs_chdir("..");
}
